### PR TITLE
Allow global overloading for server request

### PR DESCRIPTION
**Pull request by shadowhand**
There are situations where the global values may need to be overloaded.

Refs #18
Refs #20

### CODE REVIEW

**Comment by oscarotero** [comment]
I miss the argument to the body stream to open a temporary stream instead php://input. For example:

``` php
list($server, $query, $parsedBody, $cookies, $files) = $serverRequestData;
$body = fopen('php://temp', 'r+');
$request = $factory->createServerRequestFromGlobals($server, $query, $parsedBody, $cookies, $files, $body);
```

**Comment by mindplay-dk** [comment]
@oscarotero won't `withBody()` take care of that case? The arguments for superglobals are only there in the first place because `$server` is unavoidable, due to `withServerParams()` missing from PSR-7 - adding the rest of the superglobals is strictly not necessary, but was my idea, as it seemed odd to have just one of the superglobals supported.

I [brought up the issue](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/php-fig/70j-bBIMn_E/VDBFygweBAAJ) with `missingServerParams()` on the FIG mailing list last night - I find it pretty awkward that we have to create an inconsistency in the factory interface to counter a gap in the HTTP model, I'm pushing to see if we can correct it somehow - you're welcome to chime in.

**Comment by oscarotero** [comment]
@mindplay-dk Yes, but due `php://input` is read-only and in php < 5.6 the stream only can be read once, I'm not sure whether multiple `php://input` can be opened without issues in these environments (even if they're replaced by php://temp streams inmediately).

**Comment by shadowhand** [comment]
@oscarotero that's not really a concern we should worry about. Only one global server request can be created and nothing dictates how the user will do this.

**Comment by oscarotero** [comment]
@shadowhand [As I can see](https://github.com/zendframework/zend-diactoros/blob/master/src/ServerRequestFactory.php#L68), Diactoros uses always `php://input`, so I guess this is something that cannot be changed for now.
But let's imagine, for example, a script to create serverRequests to recreate errors in a site:

``` php
$requestId = 139730;
$dir = 'logs/requests/'.$requestId;

$server = include $dir.'/_server.php';
$query = include $dir.'/_get.php';
$parsedBody = include $dir.'/_post.php';
$cookies = include $dir.'/_cookies.php';
$input = $dir.'/input.txt';

$serverRequest = $factory->createServerRequestFromGlobals($server, $query, $parsedBody, $cookies);
$serverRequest = $serverRequest->withBody($factory->createStreamFromFile($input));

$response = $dispatcher->dispatch($serverRequest);
```

In this case, `php://input` is opened in the serverRequest factory and then replaced. I'm not sure if this is a good thing, in cases we have to create serveral serverRequest for testing purposes.

The other option is to use `createServerRequest` and use the `with*` methods to add all data, but there's no way to insert the $server data (unless the argument is added to the factory)

**Comment by shadowhand** [comment]
@oscarotero you're assuming that Diactoros `ServerRequestFactory` will continue to exist in it's current form once http-factory is adopted. I am not at all sure that will be the case. However, the need for passing `$serverParams` is an interesting one that I am not sure is completely addressed.

**Comment by oscarotero** [comment]
Yes, I think server params should be passed to the ServerRequestFactory::createServerRequest as told here: https://github.com/http-interop/http-factory/pull/20#issuecomment-249440215. So, it could be perfectly possible to create a ServerRequest using global values without need to include a method for this purpose in this specification. Even could exist an independent package to do this using any psr-7 library.

**Comment by barryvdh** [comment]
I think this makes sense. It's also how @weierophinney does this in Diactoros: https://github.com/zendframework/zend-diactoros/blob/34e964b287aff2cf2ffae2abc787db8e7fbfb8af/src/ServerRequestFactory.php#L34-L75 

And alternative could be to take the Symfony way: https://github.com/symfony/symfony/blob/fdb7834f695552d4e51f2c9ea9d73eed0b77f10f/src/Symfony/Component/HttpFoundation/Request.php#L261-L399
A `createServerRequestFromGlobals()` method without parameters that uses the superglobals (like the current interface) and add the paramaters as optional to the regular create: 

``` php
createServerRequest($method, $uri, array $server = null, array $query = null, array $body = null, array $cookies = null, array $files = null)
```

Or just the `$server` parameter, as that is the only one which can't be changed later:, like Guzzle/psr7 does: https://github.com/guzzle/psr7/blob/64862e854f876bc5aee2996cab2f552db8586065/src/ServerRequest.php#L156-L181

`createServerRequest($method, $uri, array $server = [])` 

The last one is probably the cleanest / in line with the rest, just as @oscarotero suggested.

**Comment by shadowhand** [comment]
@barryvdh I think the Guzzle style makes the mose sense.

**Comment by shadowhand** [comment]
I am closing this in favor of adding `array $server = null` parameter to `ServerRequestFactoryInterface`.

**Pull request closed without merging**
