### PR TITLE
Make createResponse consistent with withStatus

### LINKED ISSUE #37: Should createResponse include a parameter for the reason phrase?
I don’t know why I didn’t run into this previously. Currently when I use `createResponse` I have to follow it up with a PSR-7 `withStatus` call to ensure a reason phrase is set:

```php
(new ResponseFactory)->createResponse(404)
    ->withStatus(404, 'Not Found');
```

This means I am double-declaring the status code, but I can’t get around that because the status code is mandatory in `withStatus`. Would it not make more sense for `createResponse` to also allow the user to set the reason phrase?

A reason phrase is not required for a minimal valid HTTP response, and I am not sure if the factory needs to be expanded just to save on a single PSR-7 method call. #9 would suggest no. I still wanted to bring up this specific case because of the weird way there PSR-7 does not allow us to add only a reason phrase and forces the redeclaration of the status code.

If it is decided that `createResponse` should **not** allow a reason phrase to be set, should the DocBlock specify what implementations need to do? Is it supposed to follow PSR-7 where “implementations MAY use the defaults as suggested in the HTTP specification”, or should the reason phrase be left empty?

### PR DESCRIPTION
**Pull request by Zegnat**
To resolve #37. I think making the PSR-17 `createResponse` match the PSR-7 `withStatus` just makes sense. Would sadden me to see this fall by the wayside.

### CODE REVIEW

**Review by mindplay-dk — APPROVED** [review]
Makes total sense.

**Comment by mindplay-dk** [comment]
Perhaps it would make sense to copy/paste the `@param` doc-blocks from [here](https://github.com/php-fig/http-message/blob/master/src/ResponseInterface.php#L45) verbatim?

**Comment by Zegnat** [comment]
I think that would make sense, but it wasn’t done for `$code` and I wasn’t sure if there was some clever reason for that. Let me just do that right now though.

**Review by shadowhand — APPROVED** [review]

**Comment by weierophinney** [comment]
Incorporated into #39.

**Pull request closed without merging**
