### PR TITLE
Change root namespace to Interop

### LINKED ISSUE #3: Use the correct namespace
Should we continue to use `Psr\Http` or would it be better to use `Interop\Http`?

cc @http-interop/http-factory-contributors

### PR DESCRIPTION
**Pull request by shadowhand**
This package does not (at this time) represent an accepted PSR.

Fixes #3

### CODE REVIEW

**Comment by weierophinney** [comment]
:+1:

**Comment by weierophinney** [comment]
@shadowhand Do I need to merge this, or can you, now that I've approved?

**Comment by harikt** [comment]
Please do add to packagist :) .

**Comment by shadowhand** [comment]
This is now merged and added to packagist.

**Pull request merged**
